### ISSUE TITLE
choose video 

### ISSUE THREAD

**Issue by markMichail** [bassemhossam/Video-Summarization#3]
can you please tell me where to put the video file or URL to summarize it 
I only found how to evaluate the model but not to test on external video

thanks

**Comment by bassemhossam** [comment]
In order to run our pipeline on a video you must run  pipeline.sh file , You need to take a look at that file and modify it with your own paths in order for it to work.
This files takes the video, extract audio and video features from the vggish model and the resnet model respectively ,it then proceeds to feed the features to our model in order to get the summary.
If you have any more questions or require any help in getting the code to work let me know.

**Comment by markMichail** [comment]
Thanks
I will try it now

Sorry for asking too much but your project is an important part in our graduation project
